import type { Metadata } from "next";
import {Inter, Manrope } from "next/font/google";
import "../../app/globals.css";
import Providers from "../Providers";
import { Toaster } from "@/components/ui/sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{lang: string}>
}>) {
  const {lang} = await params
  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${inter.variable} ${manrope.variable} antialiased`}
      >
        <Providers lang={lang}>
          {children}
        </Providers>
        <Toaster position="top-center" richColors/>
      </body>
    </html>
  );
}
